import { readFileSync } from "node:fs";
import path from "node:path";
import ButtonLink from "@/components/ButtonLink";
import Callout from "@/components/Callout";
import InitExplorer from "@/components/InitExplorer";
import ContactCtas from "@/components/ContactCtas";
import SpotlightCard from "@/components/SpotlightCard";
import CtaBand from "@/components/CtaBand";
import Section from "@/components/Section";
import WrapToggle from "@/components/WrapToggle";
import { pageMetadata } from "@/lib/metadata";
import { GITHUB_URL } from "@/site.config";

export const metadata = pageMetadata({
  title: "Integrations",
  description:
    "What Fourgate works with today: local stdio MCP servers, HTTP GET read-back with Bearer, custom-header or Basic auth, and GitHub Issues read-back. Plus what is not supported yet.",
  path: "/integrations",
});

// Generated by `fourgate init` (0.3.0) with the README's example flags; read at build time.
const example = (name: string) => readFileSync(path.join(process.cwd(), "src/content/init-example", name), "utf8").trimEnd();

// The explorer re-prints each file with JSON.stringify(…, null, 2); fail the build if that
// would differ by a single character from the file `fourgate init` actually wrote.
const initFiles = (["readback.json", "runtime.json", "scan.json"] as const).map((name) => {
  const raw = example(name).split(String.fromCharCode(13)).join("");
  if (JSON.stringify(JSON.parse(raw), null, 2) !== raw) throw new Error(`${name}: display would differ from the generated file`);
  return { name, raw };
});

const initCommand = `fourgate init --tool create_issue --test-account disposable-demo \\
  --id-path result.structuredContent.id \\
  --readback-url 'https://api.example.com/issues/{record_id}' \\
  --expect title=title --arg title=FOURGATE-SCAN-TEST \\
  --token-env READBACK_TOKEN --missing-status 404 \\
  -- python your_server.py`;

const today = [
  {
    title: "Local stdio MCP servers",
    text: "Any MCP server launched as a local stdio process with a command. fourgate guard wraps that command at runtime; fourgate scan exercises contracted writes against a disposable test account.",
  },
  {
    title: "HTTP GET read-back",
    text: "A bounded GET to an API that can return the written record. The read credential is sent as a Bearer token by default, or as a custom header (for example X-Api-Key) or Basic auth, or with no auth. Fixed, non-secret headers such as an API version can be added; credential-looking header names are rejected there, so a token can only come from an environment variable.",
  },
  {
    title: "GitHub Issues read-back",
    text: "A built-in read-back type for GitHub Issues. The bundled GitHub contract is a template: it still needs a disposable repository, tokens and real end-to-end acceptance.",
  },
  {
    title: "Local command verifier",
    text: "A trusted local command that receives only the contract-selected fields. The bundled one, fourgate.verify_http, is the generic HTTP read-back above.",
  },
  {
    title: "CI template",
    text: "A copy-paste GitHub Actions workflow that runs fourgate scan on manual dispatch and fails the job on any FAIL or UNKNOWN. Fourgate's own CI runs its steps against the bundled demo fixture; it has not yet been run against a hosted connector.",
  },
];

const notYet = [
  "Remote MCP transport (HTTP-based MCP servers). Only command-configured local stdio servers are covered.",
  "Non-HTTP databases. There are no database adapters; read-back is an HTTP GET.",
  "Generated contracts. Outcome contracts are written by hand and approved by a human.",
  "Dashboards, alerting, a gateway, a retry engine or automatic compensation.",
];

export default function IntegrationsPage() {
  return (
    <>
      <Section
        id="top"
        as="h1"
        rule={false}
        title="Works with any system that exposes a GET endpoint for the written record."
        intro={
          <p>
            Fourgate does not need a vendor-specific connector to check an outcome. If your system of record can return the
            record your agent just wrote, over HTTPS, Fourgate can read it back and compare the contracted fields.
          </p>
        }
      >
        <ul className="grid gap-3 md:grid-cols-2">
          {today.map((t, i) => (
            <SpotlightCard as="li" key={t.title} className={`rounded-[14px] border border-line bg-surface p-5 ${i === 0 ? "md:col-span-2" : ""}`}>
              <h2 className="font-medium text-foreground">{t.title}</h2>
              <p className="mt-1.5 text-small text-muted">{t.text}</p>
            </SpotlightCard>
          ))}
        </ul>
      </Section>

      <Section
        id="wrap"
        title="Wrap your server."
        intro={<p>Your MCP client keeps its entry for the server. Only the command changes: fourgate guard runs your server behind it.</p>}
      >
        <WrapToggle />
      </Section>

      <Section
        id="config"
        layout="stack"
        title="One write tool, one read-back, two small files."
        intro={
          <p>
            <code className="code-inline">fourgate init</code> writes these from flags, validates them with the same loaders
            scan, guard and doctor use, and never reads secret values, starts the server or contacts an endpoint. The files
            contain only the name of the credential&apos;s environment variable.
          </p>
        }
      >
        <div className="max-w-3xl">
          <Callout tone="caution" title="Configuration example, not a tested vendor integration">
            <p>
              These files were generated by running the command below with fourgate 0.3.0. The endpoint{" "}
              <code>api.example.com</code> and <code>your_server.py</code> are placeholders. Point them at your own API and
              server, then prove the contract on a disposable test account with <code>fourgate scan</code>.
            </p>
          </Callout>
        </div>
        <div className="mt-6">
          <InitExplorer command={initCommand} files={initFiles} />
        </div>
        <dl className="mt-8 max-w-3xl">
          {[
            ["secret_env", "Lists the read credential's variable. fourgate guard removes it from the MCP server's environment; the verifier still receives it."],
            [
              "missing_statuses: [404]",
              "Opts a 404 into FAIL. Only do this after confirming the read-only identity can see the relevant records; otherwise a missing record and missing access look alike.",
            ],
            ["timeout_ms", "At most 1500 for the read-back; the runtime caps each verifier at 2000 ms. Anything slower is UNKNOWN."],
          ].map(([k, v]) => (
            <div key={k} className="grid gap-1 border-t border-line py-4 sm:grid-cols-[13rem_1fr] sm:gap-8">
              <dt>
                <code className="code-inline">{k}</code>
              </dt>
              <dd className="text-small text-muted">{v}</dd>
            </div>
          ))}
        </dl>
      </Section>

      <Section id="not-yet" title="Not supported yet">
        <ul>
          {notYet.map((n) => (
            <li key={n} className="border-t border-line py-4 text-muted last:border-b">
              {n}
            </li>
          ))}
        </ul>
        {GITHUB_URL && (
          <div className="mt-6">
            <ButtonLink href={`${GITHUB_URL}#current-limitations`} variant="text">
              Current limitations in the README
            </ButtonLink>
          </div>
        )}
      </Section>

      <CtaBand title="Not sure your API has the right GET endpoint?" text={<p>Finding the read-back endpoint for each write is part of the scope call.</p>}>
        <ContactCtas />
      </CtaBand>
    </>
  );
}
